version: '2'

services:
  db1:
    image: sath89/oracle-12c
    hostname: db1
    ports:
      - "5501:8080"
    volumes:
      - ./db1/share/:/home/oracle/share/:ro
  db2:
    image: sath89/oracle-12c
    hostname: db2
    ports:
      - "5502:8080"
    volumes:
      - ./db2/share/:/home/oracle/share/:ro
